#!/usr/bin/env node
import Database from 'better-sqlite3';
import { join } from 'path';
import { randomUUID } from 'crypto';

const DB_FILE = join('.', 'data/lovioa.db');
const db = new Database(DB_FILE);

const prompts = [
  { id: 'p621', prompt: 'Portrait: a master glassblower on the island of Murano shaping a pendant chandelier ornament at the end of a blowpipe, the molten glass glowing orange-red in a dark workshop, the breath creating the precise curve of the form. Shot on Leica SL2, 85mm f/1.4. A craft that has been practiced on the same island for seven hundred years, forbidden to leave Venice on pain of death. Glass as the most transformed of materials — sand becoming liquid becoming solid, taking any shape the breath can imagine. The oldest high-tech industry.' },
  { id: 'p622', prompt: 'Abstract: an electron microscope photograph of an influenza virus particle breaking through a cell membrane, the spike proteins piercing the lipid bilayer, the viral particle in the moment of successful infection. Colored by electron microscopy software. The most successful parasite in human history. A pathogen that kills between 250,000 and 500,000 people each year and has never been eradicated. Biology at the scale of a few hundred nanometers. The war between virus and cell at molecular resolution.' },
  { id: 'p623', prompt: 'Landscape: the Salar de Uyuni salt flats in Bolivia at sunrise, the thin layer of water on the salt crust turning into a perfect mirror, the sky reflected with absolute fidelity, the mountains on the horizon visible both above and below the waterline. Shot on Phase One IQ4, 85mm. The largest mirror on Earth. The flattest surface on Earth, used to calibrate the sensors of orbiting satellites. A desert that was once a lake, now a crystalline crust covering ten thousand square kilometers. The horizon made meaningless by perfect flatness.' },
  { id: 'p624', prompt: 'Portrait: a female volcanologist monitoring an active eruption from a safe distance, the lava fountain behind her reaching 50 meters, the ash falling, her instruments recording gas emissions and seismic data in real time. Shot on Canon R5, 35mm f/1.4. A science practiced at the edge of what is survivable. Volcanoes that erupt for months and can only be observed from a few kilometers away. The raw power of the Earth interior made visible in the eruption of a volcano. A field scientist watching the planet most dramatic moments.' },
  { id: 'p625', prompt: 'Portrait: a master Viennese coffee house barista at a traditional establishment, the coffee prepared on a charcoal-fired machine from 1952, the foam drawn into a perfect rosetta, the small glass of water served alongside, the marble counter worn by a century of elbows. Shot on Leica Q3, 28mm Summilux. The coffee house that was the intellectual center of the Austro-Hungarian Empire. Where Freud sat and wrote, where Trotsky plotted revolution, where Mahler composed. Coffee as the fuel of civilization. The ritual of sitting for hours over a single cup that changes the way you think.' },
  { id: 'p626', prompt: 'Street: the Shanghai Railway Station at the peak of Lunar New Year migration, the crowds so dense the movement is collective rather than individual, dozens of faces visible in the crowd, everyone carrying the same colored bags, the announcement system in Mandarin and Cantonese echoing in the vaulted ceiling. Shot on Fujifilm X100VI, 23mm f/2. The largest annual human migration on Earth. A billion trips in forty days. The family reunion that drives the behavior of 1.4 billion people for two weeks every year. A country in motion.' },
  { id: 'p627', prompt: 'Abstract: a composite photograph of a solar flare and coronal mass ejection from NASA Solar Dynamics Observatory, the plasma arc extending 500,000 kilometers from the Sun surface, the scale made comprehensible by comparison to the Earth rendered below at true scale. Composite of SDO AIA 171 and AIA 131 angstrom images. The energy released in a single coronal mass ejection equals that of 10 billion nuclear bombs. Our star being violent at the scale of our entire planet. The most powerful event in the solar system, photographed at the only distance where it can be seen clearly.' },
  { id: 'p628', prompt: 'Editorial: a fashion editorial shot inside a natural ice cave in the Austrian Alps, models in haute couture evening wear, the ice formations creating an otherworldly architecture, the cold breath visible in the sub-zero air, furs and silk against frozen rock. Shot on Phase One IQ4, 85mm f/2. Fashion at the most extreme natural venue. Haute couture in a space carved by glaciers over ten thousand years. The contradiction of the most delicate fabrics in the most extreme cold. Climate change made literal — the ice cave that may not exist in thirty years.' },
  { id: 'p629', prompt: 'Portrait: a master Damascus steel maker in Fez working the pattern-welded steel by traditional methods, folding the layers of high-carbon and low-carbon steel, the watermark pattern emerging in the heated metal as it is folded and forge-welded repeatedly. Shot on Leica SL2, 50mm APO. The steel that gave swords their legendary reputation in the medieval world. A technique lost for 200 years and rediscovered in the 1990s by metallurgists examining ancient blades under electron microscopes. The pattern in the steel as the record of how many times it has been folded. Science validating ancient craft.' },
  { id: 'p630', prompt: 'Landscape: an active volcano on Stromboli in Italy erupting at night, the lava fountain shooting hundreds of meters into the air, the molten rock lighting the night sky orange, the sea visible below the cliffs, a small boat in the harbor below. Shot on Phase One IQ4, 85mm. The volcano that has been erupting continuously for at least 2,000 years — the only eruptions the ancient Romans and Greeks ever saw and recorded. The island where the word volcano originates. Living geology, still active, still dangerous, still producing the land as it destroys it.' },
  { id: 'p631', prompt: 'Portrait: a female climate scientist extracting an ice core from the Greenland ice sheet at minus 25 degrees Celsius, the core held up against the light showing the layers of annual snow accumulation, each layer a year of trapped atmosphere, each bubble a sample of the ancient sky. Shot on Canon R5, 50mm f/1.2. Reading the climate record of the last 800,000 years from a cylinder of ice. CO2 levels from 400,000 years ago preserved in the bubbles. The most direct evidence of climate cycles over Earth history. A scientist holding a million years of atmospheric data in a cylinder of ice.' },
  { id: 'p632', prompt: 'Abstract: a long-exposure photograph of bioluminescent waves crashing on a beach in the Maldives, the plankton activated by the motion of the water creating bright blue light streaks in the breaking waves, the Milky Way visible above the horizon. Shot on Sony A7S III, 30s exposure. The chemical reaction between algae and sea water that produces light. A beach that glows blue for a few seconds every wave. The smallest life-form creating the most dramatic light show on Earth. Biology as the source of light in the darkness.' },
  { id: 'p633', prompt: 'Portrait: a musicologist in Vienna analyzing Mozart original manuscript for the Requiem, the handwritten score visible under a magnifying loupe, the corrections and unfinished passages marked in the margin by Mozart own hand, the paper yellowed and fragile. Shot on Leica M11, 50mm Noctilux. The last composition Mozart ever wrote, unfinished at his death. The mystery of who completed which passages, still debated by scholars. A composer writing music for his own funeral, knowing it. The Requiem that contains within it the echo of Mozart death.' },
  { id: 'p634', prompt: 'Street: a flooded market in Bangkok after the annual monsoon, the vendors wading knee-deep in brown water, the goods piled high on the market stalls above the waterline, customers arriving in small boats, the city functioning as it always does despite the water. Shot on Fujifilm X-T5, 35mm f/2. The most flood-resilient city on Earth. A culture that has adapted to six months of water each year for centuries. Business continuing in two feet of water. The market as a demonstration of human adaptability at its most practical.' },
  { id: 'p635', prompt: 'Abstract: an X-ray crystallography image of a DNA double helix, the phosphate backbone visible as the two ribbons, the base pairs connecting them visible as horizontal rungs, the image colored by a coloring algorithm used by structural biologists. The molecule that contains the instructions for building every living thing on Earth. The structure discovered by Watson and Crick that changed the understanding of life. A molecule 2 nanometers wide and meters long if stretched out. The code of life rendered in diffraction patterns and colored by software.' },
  { id: 'p636', prompt: 'Fashion: a fashion editorial featuring digital fashion garments designed for the metaverse — clothing that only exists as pixels, rendered on models in virtual photography environments, the garments made of impossible materials and impossible geometries that cannot physically exist. Shot with Unreal Engine 5 real-time rendering, photographed as if real. Fashion that exists only on screens. Garments designed without the constraints of physics or textile engineering. The first fashion designed for an environment where the laws of gravity and material science do not apply.' },
  { id: 'p637', prompt: 'Portrait: a master indigo textile dyer in the ancient city of Kano in northern Nigeria, the vat of fermented indigo dye beside her, the cloth being lifted from the dye with green fabric that will oxidize to blue in the air, her hands stained deep blue. Shot on Leica Q3, 28mm Summilux. The oldest synthetic pigment in human history — invented in India around 4000 years ago and used to dye cloth in Kano for six hundred years. The chemistry of oxidation that makes the green thread turn blue. A craft that has been practiced in this city for longer than most countries have existed.' },
  { id: 'p638', prompt: 'Street: an underground jazz club in the West Village, New York, at 2am, the band on a small stage, the smoke machine adding atmosphere to the low light, the regulars at the bar with their whiskey, the intimacy of music in a space that holds fifty people. Shot on Leica M11, 35mm Summilux. The music that defined the cultural identity of a city. Jazz born in New Orleans, grown in Chicago, and made permanent in New York. The last set of the night, when the crowd is smallest and the musicians play most freely. A scene that has been repeating since 1950.' },
  { id: 'p639', prompt: 'Abstract: a composite photograph of the aurora borealis over northern Norway, shot simultaneously in visible light and infrared, the visible light showing the familiar curtains of green and purple, the infrared revealing the heat signature of the upper atmosphere where the solar particles collide with gas molecules at 300 kilometers altitude. Composite of two exposures, visible and thermal. The light show created by the solar wind hitting the Earth magnetosphere. An event that has inspired myths and religions for as long as humans have lived far enough north to see it. The atmosphere as a screen for the Sun energy.' },
  { id: 'p640', prompt: 'Editorial: a fashion editorial shot inside the cooling tower of a decommissioned nuclear power plant in France, the honeycomb concrete structures rising sixty meters, the graffiti from decommissioning workers visible, the scale of the space making the fashion models seem small, industrial monumentalism meeting haute couture. Shot on Phase One IQ4, 85mm f/2. The architecture of atomic energy as a fashion venue. Nuclear power as the most consequential technology of the 20th century — the promise of unlimited energy, now a relic. The tower that once contained the steam that drove turbines now containing fashion and memory. Energy made into aesthetic.' },
];

const insert = db.prepare(`
  INSERT INTO gen_jobs
    (id, user_id, mode, model, size, quality, prompt, negative_prompt, reference_image_url, status, attempt_count, max_attempts, queued_at, created_at, updated_at)
  VALUES (?, NULL, 'text', 'gpt-image-2', '1024x1024', 'medium', ?, '', NULL, 'queued', 0, 5, ?, ?, ?)
`);

const now = new Date().toISOString();
let added = 0;
for (const p of prompts) {
  const id = randomUUID();
  try {
    insert.run(id, p.prompt, now, now, now);
    added++;
    console.log('  + ' + p.id);
  } catch(e) {
    console.log('  x ' + p.id + ': ' + e.message.slice(0, 50));
  }
}
console.log('\nAdded:', added, '/', prompts.length);

const r = db.prepare("SELECT status, COUNT(*) as c FROM gen_jobs GROUP BY status ORDER BY status").all();
r.forEach(x => console.log('  ' + x.status + ': ' + x.c));
const total = db.prepare("SELECT COUNT(*) as c FROM gen_jobs").get();
console.log('  Total:', total.c);
db.close();