#!/usr/bin/env node
import Database from 'better-sqlite3';
import { join } from 'path';
import { randomUUID } from 'crypto';

const DB_FILE = join('.', 'data/lovioa.db');
const db = new Database(DB_FILE);

const prompts = [
  { id: 'p641', prompt: 'Portrait: a master ebru artist in Istanbul creating paper marbling on the surface of a tray of thickened water, the drops of oil paint being combed into precise organic patterns, the pattern forming a botanical design of tulips and leaves, the paper being laid on the surface to transfer the design. Shot on Leica SL2, 85mm f/1.4. The art of floating paint on water, practiced in Istanbul since the 16th century. A technique that can only be performed once — each marbled paper unrepeatable. The pattern that looks like marble but is in fact the record of the exact moment the paint was dropped. Ephemeral art made permanent by paper.' },
  { id: 'p642', prompt: 'Abstract: the Pillars of Creation in the Eagle Nebula, photographed by the James Webb Space Telescope, the massive columns of gas and dust lit by the ultraviolet radiation of young stars, the miniature solar systems forming within the dust, the scale of the structures compared to the light-years of empty space around them. Composite of JWST NIRCam and MIRI images. The most iconic astronomical image of the modern era. Star formation happening in real time at a scale that makes the human mind struggle. The nursery of stars that are being born 6,500 light-years away. Creation in the act of creating.' },
  { id: 'p643', prompt: 'Landscape: Antelope Canyon in Arizona at noon, the beam of sunlight piercing through the narrow slot in the sandstone above, the light shaft illuminating the swirling red-orange wave patterns carved by water over millions of years, the dust particles visible in the light beam. Shot on Phase One IQ4, 24mm f/8. The sandstone that was once a sand dune, then compressed into rock, then carved by flash floods into shapes that look like liquid frozen in time. A canyon that exists only for a few minutes each day when the sun is at the exact angle to send a beam through the slot. The most photographed slot canyon on Earth.' },
  { id: 'p644', prompt: 'Portrait: a female oceanographer deploying a research buoy from the deck of a research vessel in the North Atlantic, the buoy hanging from a crane over the grey ocean, the instruments visible on its frame, the wind whipping her hair, the horizon empty in every direction. Shot on Canon R5, 35mm f/1.4. The ocean that covers 71% of the Earth surface and is the least understood environment on the planet. Buoys that measure the temperature, salinity, and current speed of the ocean at different depths, transmitting the data by satellite. The data that tells us how fast the ocean is warming. Science on a boat in the most remote place on Earth.' },
  { id: 'p645', prompt: 'Portrait: a master zellige tile maker in Fez arranging geometric tiles in a traditional courtyard, each tile individually cut and glazed, the pattern being assembled one piece at a time in a herringbone arrangement, the completed sections visible on the floor around her. Shot on Leica Q3, 28mm Summilux. The tile work that covers the floors and walls of every Moroccan mosque and madrasa. A craft that requires years of apprenticeship — a master tile maker can look at a geometric pattern and calculate the exact cuts needed without drawing. Islamic geometric art as mathematical proof. The complexity that emerges from simple rules applied with precision.' },
  { id: 'p646', prompt: 'Street: Shinjuku Kabukicho entertainment district at 11pm, the neon signs reflecting on the wet pavement, the crowds moving between establishments, the dragon lanterns above the narrow streets, the contrast between the traditional Japanese gate architecture and the LED advertisements. Shot on Fujifilm X100VI, 23mm f/2. The largest entertainment district in Asia. A neighborhood that was rebuilt from the ruins of the wartime era to become a monument to commercial pleasure. The streets where salarymen drink after work and tourists seek entertainment. A square kilometer that processes a million people every weekend night.' },
  { id: 'p647', prompt: 'Abstract: a 3D visualization of a mushroom mycelium network in forest soil, the thread-like hyphae connecting individual fungal spores across a cubic meter of earth, the nodes representing nutrient exchange points, colored by nutrient flow rate from blue to red. Rendered from micro-CT scan data of forest soil. The fungal network that connects trees in a forest, allowing them to share nutrients and chemical signals. A single organism that can cover hundreds of hectares. The wood wide web that forest ecologists have mapped over the past thirty years. Communication through chemistry, trade in carbon and phosphorus.' },
  { id: 'p648', prompt: 'Editorial: a fashion editorial shot in an abandoned shopping mall in Hong Kong that closed during the pandemic, the empty storefronts with their brand names still visible, the escalators stopped and overgrown, the skylights broken and plants growing through the floors, the contrast between the brand-new fashion and the decayed commercial architecture. Shot on Phase One IQ4, 85mm f/2. The death of retail in the age of e-commerce. A mall that was once one of the most commercially dense places on Earth, now empty and growing plants. Fashion as the last gasp of the physical shopping experience. Beauty in the ruins of commerce.' },
  { id: 'p649', prompt: 'Portrait: a master watchmaker in Geneva assembling a tourbillon movement under a loupe, the hundreds of tiny components laid out in an organized tray, the tweezers holding a balance wheel the size of a fingernail, the movement on a white anti-static mat. Shot on Leica M11 with macro, 90mm f/2.8. The most complex mechanical watch movement, designed to cancel out the effect of gravity on the timekeeping. A mechanism with hundreds of parts, each machined to tolerances of a few microns. A craft that dates to 1795 and has never been fully automated. The most precise machines ever made by human hands.' },
  { id: 'p650', prompt: 'Landscape: the Devi Posta waterfall in Nepal during monsoon season, the water volume so enormous the entire valley shakes with the sound, the spray rising hundreds of meters, the surrounding jungle a saturated emerald green, the river below swollen and brown with silt from the Himalayas. Shot on Phase One IQ4, 85mm. The monsoon that feeds a billion people agriculture, filling rivers that irrigate fields across South Asia. Water that fell as snow on Kangchenjunga and became a river in hours. The most powerful seasonal weather event in the world. A waterfall at its absolute maximum — everything the mountain has to give, given in a single season.' },
  { id: 'p651', prompt: 'Portrait: a female aerospace engineer at Cape Canaveral in a clean room suit during the final integration of a spacecraft, the rocket visible in the background through the clean room windows, her tablet showing schematics, the team of technicians in identical suits around her. Shot on Canon R5, 35mm f/1.4. The most complex machine ever built by human beings — a rocket that must function perfectly in the vacuum of space. The engineer who helped design a system that costs $4,000 per kilogram to launch. The dream of reaching orbit that became a career. The last days before launch when every decision could mean success or catastrophic failure.' },
  { id: 'p652', prompt: 'Abstract: polarized light microscopy of liquid crystal phases, the colors produced by the interference of polarized light as it passes through the ordered molecular structures of different liquid crystal phases — smectic, nematic, and cholesteric — each phase producing a distinct color signature. Photographed under crossed polarizers. The state of matter that exists between liquid and solid — a fluid with the optical properties of a crystal. The technology behind every LCD screen on Earth. Molecular order producing optical beauty. The physics of displays that process visual information for billions of people every day.' },
  { id: 'p653', prompt: 'Portrait: a master hat maker in Milan shaping a felt fedora on a wooden block using steam and a bocking iron, the steam rising from the felt, the precise movements of the hands forming the crown and brim, the walls covered with hat blocks of every shape and size. Shot on Leica Q3, 28mm Summilux. The hat that was the defining accessory of the 20th century — worn by gangsters and detectives, diplomats and dictators, film stars and workers. A craft that declined almost to nothing with the rise of casual dress and is now maintained by a small number of ateliers. The skill of knowing exactly how the steam and pressure will transform the felt into a specific shape.' },
  { id: 'p654', prompt: 'Street: a Bangkok night market street food stall at midnight, the vendor cooking pad thai on a gas burner on the sidewalk, the customers sitting on plastic stools at low tables, the overhead power lines hanging in tangled bundles, the street illuminated by the stall burner flame and a single overhead fluorescent tube. Shot on Fujifilm X-T5, 35mm f/2. The cheapest and most delicious food in the world, prepared on a sidewalk by people who have been cooking the same dish for thirty years. A meal for a dollar that is better than anything in any restaurant. The night market as the most democratic of dining rooms.' },
  { id: 'p655', prompt: 'Abstract: scanning electron microscopy of red blood cells flowing through a capillary, the deformable biconcave discs squeezing through a channel narrower than their own diameter, the individual cells distinguishable and moving in single file, colored by false-color electron microscopy software. The mechanism that allows blood cells to reach every capillary in the human body, even the smallest vessels. Each cell must deform to pass through spaces smaller than itself. A journey of 20,000 kilometers of blood vessels navigated by cells that are 8 microns in diameter. Life at the scale of the invisible.' },
  { id: 'p656', prompt: 'Fashion: a fashion editorial featuring garments made from holographic and iridescent materials, the fabrics shifting color as the models move, shot in a white cyclorama studio with multiple light sources creating the full spectrum of reflections, the models wearing nothing but the garments and minimal jewelry. Shot on Phase One IQ4, 85mm f/2. The material that exists between light and surface — fabrics that contain no pigment but produce color through the interference of light waves. The fashion industry search for surfaces that have never existed before. A garment that is different every time you look at it. Iridescence as the most beguiling of fashion statements.' },
  { id: 'p657', prompt: 'Portrait: a master clock restorer in Florence working on a 17th-century astronomical clock, the mechanisms visible through the open case, the gears worn smooth from centuries of use, the hands positioned at an incorrect time because it has not run for decades, the tools from a different century laid beside it. Shot on Leica M11 with macro, 90mm f/2.8. The clock that told the time of the Medicis. Clocks that have been measuring time in the same position for three hundred years. The act of bringing back to life something that has been silent since before the industrial revolution. A craft that requires both the engineering knowledge to understand the original mechanism and the artisanal skill to repair it.' },
  { id: 'p658', prompt: 'Street: the Star Ferry crossing Victoria Harbour in Hong Kong at dusk, the Kowloon skyline behind the ferry, the light from the buildings beginning to illuminate, the windows of the financial towers turning on one by one, the ferry commuters on the deck watching the city transform. Shot on Fujifilm X100VI, 23mm f/2. The ferry that has been crossing the harbour since 1898. A journey of eight minutes that costs HK$3.20 and has been priced below inflation for decades. The most iconic view in Asia — the skyline that appeared on every postcard of Hong Kong for a hundred years. A commute that is also a tourist attraction.' },
  { id: 'p659', prompt: 'Abstract: a cross-section diagram of a quantum computer dilution refrigerator, the concentric cylindrical stages labeled and cut away to show the decreasing temperature from room temperature at the top to 15 millikelvin at the bottom, the superconducting qubits visible in the lowest stage, the cable harness threading through each stage. Technical illustration rendered in the style of a scientific journal cover. The coldest place in the known universe — colder than outer space. The refrigerator that must cool quantum processors to temperatures close to absolute zero to maintain quantum coherence. The machine that Google claims will achieve quantum supremacy. Physics at the edge of what is achievable.' },
  { id: 'p660', prompt: 'Editorial: a fashion editorial shot in an abandoned theme park outside Osaka, the rollercoaster tracks rusting and overgrown, the theme park mascots faded and peeling, the carousel horses frozen mid-rotation, the fashion models wandering through the space as if they are the last people on Earth discovering the ruins of entertainment. Shot on Phase One IQ4, 85mm f/2. The theme park that was supposed to bring joy and instead brought debt. The architecture of fun now being reclaimed by vegetation. Fashion as an elegy for consumer culture. The last visitors to the park that no one visits anymore.' },
];

const insert = db.prepare(`
  INSERT INTO gen_jobs
    (id, user_id, mode, model, size, quality, prompt, negative_prompt, reference_image_url, status, attempt_count, max_attempts, queued_at, created_at, updated_at)
  VALUES (?, NULL, 'text', 'gpt-image-2', '1024x1024', 'medium', ?, '', NULL, 'queued', 0, 5, ?, ?, ?)
`);

const now = new Date().toISOString();
let added = 0;
for (const p of prompts) {
  const id = randomUUID();
  try {
    insert.run(id, p.prompt, now, now, now);
    added++;
    console.log('  + ' + p.id);
  } catch(e) {
    console.log('  x ' + p.id + ': ' + e.message.slice(0, 50));
  }
}
console.log('\nAdded:', added, '/', prompts.length);

const r = db.prepare("SELECT status, COUNT(*) as c FROM gen_jobs GROUP BY status ORDER BY status").all();
r.forEach(x => console.log('  ' + x.status + ': ' + x.c));
const total = db.prepare("SELECT COUNT(*) as c FROM gen_jobs").get();
console.log('  Total:', total.c);
db.close();