export const BILLING_PLANS = [
  {
    id: 'starter_cny',
    tierId: 'starter',
    displayName: '入门套餐',
    price: 1000,
    currency: 'cny',
    credits: 66,
    fastCredits: 66,
    imagePrice: 0.15,
    popular: false,
    features: [
      '一次性购买，永久有效',
      '约 66 张 AI 图片',
      '每张约 ¥0.15',
    ],
  },
  {
    id: 'standard_cny',
    tierId: 'standard',
    displayName: '标准套餐',
    price: 2000,
    currency: 'cny',
    credits: 166,
    fastCredits: 166,
    imagePrice: 0.12,
    popular: true,
    features: [
      '一次性购买，永久有效',
      '约 166 张 AI 图片',
      '每张约 ¥0.12',
    ],
  },
  {
    id: 'premium_cny',
    tierId: 'premium',
    displayName: '高级套餐',
    price: 9900,
    currency: 'cny',
    credits: 990,
    fastCredits: 990,
    imagePrice: 0.1,
    popular: false,
    features: [
      '一次性购买，永久有效',
      '约 990 张 AI 图片',
      '每张约 ¥0.10',
    ],
  },
];
