export const CREDITS_PER_IMAGE = 5;

export const BILLING_PLANS = [
  {
    id: 'starter_cny',
    tierId: 'starter',
    displayName: '入门套餐',
    price: 1000,
    currency: 'cny',
    credits: 330,
    fastCredits: 66,
    creditsPerImage: CREDITS_PER_IMAGE,
    imagePrice: 0.15,
    coverImage: '/assets/pricing/starter-cover.jpg',
    domesticPaymentUrl: 'https://wzyp.cn/item/4fsi9y',
    popular: false,
    features: [
      '一次性购买，按月结算',
      '约 66 张 AI 图片',
      '每张约 ¥0.15',
    ],
  },
  {
    id: 'standard_cny',
    tierId: 'standard',
    displayName: '标准套餐',
    price: 2000,
    currency: 'cny',
    credits: 830,
    fastCredits: 166,
    creditsPerImage: CREDITS_PER_IMAGE,
    imagePrice: 0.12,
    coverImage: '/assets/pricing/standard-cover.jpg',
    domesticPaymentUrl: 'https://wzyp.cn/item/12wlev',
    popular: true,
    features: [
      '一次性购买，按月结算',
      '约 166 张 AI 图片',
      '每张约 ¥0.12',
    ],
  },
  {
    id: 'premium_cny',
    tierId: 'premium',
    displayName: '高级套餐',
    price: 9900,
    currency: 'cny',
    credits: 4950,
    fastCredits: 990,
    creditsPerImage: CREDITS_PER_IMAGE,
    imagePrice: 0.1,
    coverImage: '/assets/pricing/premium-cover.jpg',
    domesticPaymentUrl: 'https://wzyp.cn/item/dq7twp',
    popular: false,
    features: [
      '一次性购买，按月结算',
      '约 990 张 AI 图片',
      '每张约 ¥0.10',
    ],
  },
];
